config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "authors#index"
  # get "/authors", to: "authors#index"

  resources :authors
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
  validates :name, presence: true

  scope :find_by_name, ->(query) do
    where("name LIKE ?", "%#{sanitize_sql_like(query)}%")
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, counter_cache: true
  validates :title, presence: true

  scope :find_by_title, ->(query) do
    where("title LIKE ?", "%#{sanitize_sql_like(query)}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
  def render_not_found
    render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  include Pagy::Backend
  include SessionsHelper

  before_action :set_author, only: [:edit, :update, :destroy]

  def index
    @query = params[:query]

    @authors = Author.all
    @authors = @authors.find_by_name(@query) if @query

    @pagy, @authors = pagy(@authors)
  end

  def show
    begin
      @author = Author.includes(:books).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render_not_found
    end
    store_redirect_url(:add_book)
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to authors_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @author.update(author_params)
      redirect_to author_path(@author)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @author.destroy
    redirect_to authors_path, status: :see_other
  end

  private

  def set_author
    @author = Author.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_not_found
  end

  def author_params
    params.require(:author).permit(:name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Pagy::Backend
  include SessionsHelper

  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index

    @query = params[:query]
    @books = Book.includes(:author).all
    @books = @books.find_by_title(@query) if @query

    @pagy, @books = pagy(@books)
    store_redirect_url(:add_book)
  end

  def new
    @book = Book.new(author_id: params[:author_id])
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_back_or(:add_book, books_path)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, status: :see_other
  end

  private

  def set_book
    @book = Book.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_not_found
  end

  def book_params
    params.require(:book).permit(:title, :author_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Redirects to stored location (or to the fallback).
  def redirect_back_or(namespace, fallback_url)
    key = "redirect_url_#{namespace.to_s}".to_sym

    redirect_to(session[key] || fallback_url)
    session.delete(key)
  end

  # Stores the URL trying to be accessed.
  def store_redirect_url(namespace)
    key = "redirect_url_#{namespace.to_s}".to_sym

    session[key] = request.original_url if request.get?
  end
end

app/views/authors/_form.html.erb
<%= form_with model: @author do |form| %>
  <%= render partial: "shared/error_messages", locals: { model: @author } %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <%= form.submit class: "btn btn-primary order-md-2" %>
    <%= link_to "Cancel", :back, class: "btn btn-outline-secondary order-md-1" %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class="container">
  <%= render "authors/form" %>
</div>

app/views/authors/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Authors</h1>
    <%= link_to "Add new author", new_author_path, class: "btn btn-primary" %>
  </div>
  <div class="card">
    <div class="card-body">
      <%= form_with url: authors_path, method: :get, class: "d-flex", html: { role: "search" } do |form| %>
        <%= form.text_field :query, value: @query, class: "form-control me-2", type: "search", placeholder: "Search", "aria-label": "Search" %>
        <%= form.submit "Search", class: "btn btn-outline-success" %>
      <% end %>

      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Number of books</th>
          </tr>
        </thead>
        <tbody>
          <% @authors.each do |author| %>
            <tr>
              <th scope="row"><%= author.id %></th>
              <td><%= link_to author.name, author %></td>
              <td><%= author.books_count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="mt-3">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/authors/new.html.erb
<div class="container">
  <h1>Add a new author</h1>
  <%= render "authors/form" %>
</div>

app/views/authors/show.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h1><%= @author.name %></h1>
    <div>
      <%= link_to "Add new book", new_book_path(author_id: @author.id), class: "btn btn-primary px-3" %>
      <%= link_to "Edit author", edit_author_path(@author), class: "btn btn-primary px-3" %>
      <%= link_to "Delete author", author_path(@author), data: { turbo_confirm: "Are you sure?", turbo_method: :delete }, class: "btn btn-danger px-3" %>
      <%= link_to "Cancel", authors_path, class: "btn btn-outline-secondary order-md-1" %>
    </div>
  </div>
  <h2>Books</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
      </tr>
    </thead>
    <tbody>
      <% @author.books.each do |book| %>
        <tr>
          <th scope="row"><%= book.id %></th>
          <td><%= link_to book.title, book %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/_form.html.erb
<%= form_with model: @book do |form| %>
  <%= render partial: "shared/error_messages", locals: { model: @book } %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :author_id, class: "form-label" %>
    <%= form.collection_select :author_id, Author.all, :id, :name %>
    <%= link_to "Add new author", new_author_path, class: "btn btn-outline-primary btn-sm" %>
  </div>
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <%= form.submit class: "btn btn-primary order-md-2" %>
    <%= link_to "Cancel", :back, class: "btn btn-outline-secondary order-md-1" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <%= render "books/form" %>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Books</h1>
    <%= link_to "Add new book", new_book_path, class: "btn btn-primary" %>
  </div>
  <div class="card">
    <div class="card-body">
      <%= form_with url: books_path, method: :get, class: "d-flex", html: { role: "search" } do |form| %>
        <%= form.text_field :query, value: @query, class: "form-control me-2", type: "search", placeholder: "Search", "aria-label": "Search" %>
        <%= form.submit "Search", class: "btn btn-outline-success" %>
      <% end %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <th scope="row"><%= book.id %></th>
              <td><%= link_to book.title, book %></td>
              <td><%= link_to book.author.name, book.author %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="mt-3">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/books/new.html.erb
<div class="container">
  <h1>Add a new book</h1>
  <%= render "books/form" %>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h1><%= @book.title %></h1>
    <div>
      <%= link_to "Edit book", edit_book_path(@book), class: "btn btn-primary px-3" %>
      <%= link_to "Delete book", book_path(@book), data: { turbo_confirm: "Are you sure?", turbo_method: :delete }, class: "btn btn-danger px-3" %>
      <%= link_to "Cancel", books_path, class: "btn btn-outline-secondary order-md-1" %>
    </div>
  </div>
  <h2><%= @book.author.name %></h2>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "BookReview", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= active_link_to "Authors", authors_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= active_link_to "Books", books_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReviewApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    The form contains <%= pluralize(model.errors.count, "error") %>.
  </div>
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>